class SeedData
    attr_reader :activity_titles, :activity_descriptions, :route_titles, :route_descriptions
    def initialize()
        @activity_titles = [
            "Morning Ride Exercise",
            "Morning Run Exercise",
            "Morning Swim Exercise",
            "Morning Hike Exercise",
            "Morning Walk Exercise",
            "Morning Alpine_Ski Exercise",
            "Morning Backcountry Ski Exercise",
            "Morning Canoe Exercise",
            "Morning Crossfit Exercise",
            "Morning E-Bike Ride Exercise",
            "Morning Elliptical Exercise",
            "Morning Handcycle Exercise",
            "Morning Ice Skate Exercise",
            "Morning Inline Skate Exercise",
            "Morning Kayaking Exercise",
            "Morning Kitesurf Exercise",
            "Morning Nordic Ski Exercise",
            "Morning Rock Climb Exercise",
            "Morning Roller Ski Exercise",
            "Morning Rowing Exercise",
            "Morning Snowboard Exercise",
            "Morning Snowshoe Exercise",
            "Morning Stair-Stepper Exercise",
            "Morning Stand Up Paddling Exercise",
            "Morning Surfing Exercise",
            "Morning Velomobile Exercise",
            "Morning Virtual Ride Exercise",
            "Morning Virtual Run Exercise",
            "Morning Weight Training Exercise",
            "Morning Wheelchair Exercise",
            "Morning Windsurf Exercise",
            "Morning Workout Exercise",
            "Morning Yoga Exercise",
            "Morning Knitting Exercise",     
            "Afternoon Ride Exercise",
            "Afternoon Run Exercise",
            "Afternoon Swim Exercise",
            "Afternoon Hike Exercise",
            "Afternoon Walk Exercise",
            "Afternoon Alpine_Ski Exercise",
            "Afternoon Backcountry Ski Exercise",
            "Afternoon Canoe Exercise",
            "Afternoon Crossfit Exercise",
            "Afternoon E-Bike Ride Exercise",
            "Afternoon Elliptical Exercise",
            "Afternoon Handcycle Exercise",
            "Afternoon Ice Skate Exercise",
            "Afternoon Inline Skate Exercise",
            "Afternoon Kayaking Exercise",
            "Afternoon Kitesurf Exercise",
            "Afternoon Nordic Ski Exercise",
            "Afternoon Rock Climb Exercise",
            "Afternoon Roller Ski Exercise",
            "Afternoon Rowing Exercise",
            "Afternoon Snowboard Exercise",
            "Afternoon Snowshoe Exercise",
            "Afternoon Stair-Stepper Exercise",
            "Afternoon Stand Up Paddling Exercise",
            "Afternoon Surfing Exercise",
            "Afternoon Velomobile Exercise",
            "Afternoon Virtual Ride Exercise",
            "Afternoon Virtual Run Exercise",
            "Afternoon Weight Training Exercise",
            "Afternoon Wheelchair Exercise",
            "Afternoon Windsurf Exercise",
            "Afternoon Workout Exercise",
            "Afternoon Yoga Exercise",
            "Afternoon Knitting Exercise",     
            "Evening Ride Exercise",
            "Evening Run Exercise",
            "Evening Swim Exercise",
            "Evening Hike Exercise",
            "Evening Walk Exercise",
            "Evening Alpine_Ski Exercise",
            "Evening Backcountry Ski Exercise",
            "Evening Canoe Exercise",
            "Evening Crossfit Exercise",
            "Evening E-Bike Ride Exercise",
            "Evening Elliptical Exercise",
            "Evening Handcycle Exercise",
            "Evening Ice Skate Exercise",
            "Evening Inline Skate Exercise",
            "Evening Kayaking Exercise",
            "Evening Kitesurf Exercise",
            "Evening Nordic Ski Exercise",
            "Evening Rock Climb Exercise",
            "Evening Roller Ski Exercise",
            "Evening Rowing Exercise",
            "Evening Snowboard Exercise",
            "Evening Snowshoe Exercise",
            "Evening Stair-Stepper Exercise",
            "Evening Stand Up Paddling Exercise",
            "Evening Surfing Exercise",
            "Evening Velomobile Exercise",
            "Evening Virtual Ride Exercise",
            "Evening Virtual Run Exercise",
            "Evening Weight Training Exercise",
            "Evening Wheelchair Exercise",
            "Evening Windsurf Exercise",
            "Evening Workout Exercise",
            "Evening Yoga Exercise",
            "Evening Knitting Exercise",     
        ]
        @route_titles = [
            "Incredibly Difficult Trail Through the Mountains",
            "My Favorite San Francisco Bike Trail",
            "The search for El Dorado",
            "Up and Downs like there's no tomorrow!",
            "New York Jog",
            "Tour of Chicago for Deep Dish",
            "Raging River Run",
            "Your legs are gonna be sore in the morning",
            "Searching for Blackbeard's Gold",
            "This is one heck of a workout",
            "Miami beach run",
            "Laps around Hawaii",
            "Around the world in 80 days",
            "Shortcup to the peak of Mt. Everest",
            "Secret trip through Yosemite",
            "Hike across America",
            "Moonshiners run",
            "The Pony Express",
            "Bandit's Valley Run",
            "Border Crossings",
            "Do this when you're tired",
            "Maple syrup run",
            "Forested trail",
            "Careful of the rattlesnakes",
            "Explore this cute town",
            "Diamond run",
            "Darjeeling Express",
            "Army Rangers' Bootcamp",
            "Break a leg",
            "Usain's Workout"
        ]
    end

end