class SeedData
    attr_reader :activity_titles, :activity_descriptions, :route_titles, :route_descriptions
    def initialize()
        @activity_titles = [
            "Do the Ladies Run This?",
            "Doing it Way Big",
            "Cold Steel",
            "World War III",
            "Tasmanian Pain Coaster",
            "Big Shots",
            "Power",
            "Addicted to Danger",
            "Peel their Caps Back",
            "No Nuts No Glory",
            "Mind of a Lunatic",
            "Now I Feel Ya",
            "Forces of Nature",
            "I Seen a Man Die",
            "War Games",
            "Alive on Arrival",
            "Bleeding Hearts Club",
            "Rock City",
            "Show & Improve",
            "Circuit City",
            "Royal Flush",
            "Dirt off my Shoulders",
            "ExtraHard",
            "Suzie Q Sailaway",
            #! 
            "50 Shades of Awesome",
            "Agony of De Feet",
            "Are We There Yet?",
            "Baby Got Track",
            "Between a Walk and a Hard Pace",
            "Big Test Icicles",
            "Blister Sisters",
            "Blondes Have More Run",
            "Bodyglide, Blisters and Bengay",
            "Bringing Up the Rear",
            "Buns on the Run",
            "Chafing the Dream",
            "Chicks with Kick",
            "Cough, Hack, Wheeze",
            "Crouching Runner, Hidden Van",
            "CU @ My Pace",
            "Cunning Stunts",
            "Dangerous Curves",
            "Dashing Divas",
            "Don't Be a Smart Pass",
            "Dudes and Boobs",
            "Easier Said than Run",
            "Forty 'n Fit",
            "Get 'er Run",
            "Get Fit or Die Tryin'",
            "Got the runs",
            "Gym Class Heroes",
            "H.A.R.T. - Haulin' Ass Race Time",
            "Happy Feet",
            "Heart & Sole",
            "Hell on Heels",
            "I Thought This Was a 5k?",
            "I-B-Pro-Fun",
            "Jugs and THugs",
            "Jugs-a-Joggin",
            "Ladies from the 80's",
            "Luck B 4 Ladies",
            "Madams of Mayhem",
            "Miles to Martinis",
            "Mind over Miles",
            "My So Called Legs",
            "Naptime at the Finish Line",
            "Nerd Herd",
            "Not Fast, Just Furious",
            "Not The First Rodeo",
            "Off Like a Prom Dress",
            "Pain Killers",
            "Peanut Butter & Jelly Legs",
            "PokeyMoms",
            "Rapid Thigh Movement",
            "Road Runners",
            "Role Models",
            "Run Like the Winded",
            "Run Long and Perspire",
            "Runderpants",
            "Running on Empty",
            "Smells Like Team Spirit",
            "Sole Mates",
            "Sole Train",
            "Spark Plugs",
            "Straight Off the Couch",
            "Stunner Runners",
            "Superfeet",
            "Sweet Soles",
            "Team Spanks",
            "Speed Bumps",
            "Tenacious Turtles",
            "The Fit, The Fat & The Elderly",
            "The Road to Glory",
            "The Tightie-Whities",
            "The Trots",
            "Thong Distance Runners",
            "Tight Butts and Sweaty Nuts",
            "Training B.R.A's",
            "Training Wheels",
            "Twin Peaks",
            "Twisted Blisters",
            "Victorious Secret",
            "Village Idiots",
            "Wii Not Fit",
            "Wolf Pack",
            "Wonder Women",
            "Where's The Finish?",
            "Young Tarts and Old Farts",
            "Your Pace or Mine?",
            "Yummy Mummies",
            "Cleats & Cleavage",
            "Hit for Brains",
            "One Hit Wonders",
            "Scared hitless",
            "Sons of Pitches",
            "Goal Diggers",
            "Cleats & Cleavage",
            "Smokin' Tees and Strokin' 3s",
            "Bad Brother Muckers",
            "Dirt Digglers",
            "Dirty Old Men",
            "Mudder Fockers",
            "Mud Lite",
        ]
        @route_titles = [
            "Incredibly Difficult Trail Through the Mountains",
            "My Favorite San Francisco Bike Trail",
            "The search for El Dorado",
            "Up and Downs like there's no tomorrow!",
            "New York Jog",
            "Tour of Chicago for Deep Dish",
            "Raging River Run",
            "Your legs are gonna be sore in the morning",
            "Searching for Blackbeard's Gold",
            "This is one heck of a workout",
            "Miami beach run",
            "Laps around Hawaii",
            "Around the world in 80 days",
            "Shortcup to the peak of Mt. Everest",
            "Secret trip through Yosemite",
            "Hike across America",
            "Moonshiners run",
            "The Pony Express",
            "Bandit's Valley Run",
            "Border Crossings",
            "Do this when you're tired",
            "Maple syrup run",
            "Forested trail",
            "Careful of the rattlesnakes",
            "Explore this cute town",
            "Diamond run",
            "Darjeeling Express",
            "Army Rangers' Bootcamp",
            "Break a leg",
            "Usain's Workout"
        ]
    end

end